name: donor_blood
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  floating_bottom_navigation_bar: ^1.5.2
  http: ^1.1.0
  image_picker: ^1.0.7
  side_navigation: ^1.0.4
  # syncfusion_flutter_charts: ^24.2.7
  path_provider: ^2.1.2
  khalti_flutter: ^3.0.0
  intl: ^0.18.1
  # google_maps_flutter: ^2.5.3

  # khalti_flutter: ^3.0.0
  # intl: ^0.18.1
  # lottie: ^2.6.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
